### ISSUE TITLE
tasmota-webcam xdrv_81_webcam.ino stream should start with boundary marker

### ISSUE THREAD

**Issue by mnsuk** [arendst/Tasmota#12376]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I am attempting to process the mjpeg stream produced by tasmota-webcam. I have use two different client libraries and both report that boundary string is missing. e.g from py-mjpeg: 
`mjpeg.ProtoError: Boundary string expected, but not found`. 
Looking at the code in xdrv_81_webcam.ino and confirming by examining the HTTP headers and content in python debug shows that the boundary string is sent after each jpeg frame. E.g. the following is sent:
```
HTTP/1.1 200 OK
Content-Type: multipart/x-mixed-replace;boundary=e8b8c539-047d-4777-a985-fbba6edff11e
Content-Type: image/jpeg
Content-Length: 17281
…….(image content)
—e8b8c539-047d-4777-a985-fbba6edff11e
Content-Type: image/jpeg
Content-Length: 17291
……..(image content)
—e8b8c539-047d-4777-a985-fbba6edff11e
```
So after the headers the content goes straight to the first jpeg image headers, then a boundary, then repeats for each image. I believe that the boundary should have been sent prior to the first jpeg image too (certainly that is what expected by the source for the python libraries  I looked at). In summary the sequence should be:

headers
boundary
image
boundary
image
boundary
image
etc

whereas it is:

headers
image
boundary
image
boundary
etc

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): ___AIThinker ESP32Cam__
- [ ] Tasmota binary firmware version number used: ___9.4.0__
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: ___esptool.py__
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
20:35:22.174 RSL: RESULT = {"NAME":"AITHINKER CAM","GPIO":[4992,1,1,1,1,5088,1,1,1,1,1,1,1,1,5089,5090,0,5091,5184,5152,0,5120,5024,5056,0,0,0,0,4928,1,5094,5095,5092,0,0,5093],"FLAG":0,"BASE":1}
20:35:22.380 RSL: RESULT = {"Module":{"0":"AITHINKER CAM"}}
20:35:22.586 RSL: RESULT = {"GPIO0":{"4992":"CAM_XCLK"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"5088":"CAM_DATA1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"5089":"CAM_DATA2"},"GPIO19":{"5090":"CAM_DATA3"},"GPIO20":{"0":"None"},"GPIO21":{"5091":"CAM_DATA4"},"GPIO22":{"5184":"CAM_PCLK"},"GPIO23":{"5152":"CAM_HREF"},"GPIO24":{"0":"None"},"GPIO25":{"5120":"CAM_VSYNC"},"GPIO26":{"5024":"CAM_SIOD"}}
20:35:22.591 RSL: RESULT = {"GPIO27":{"5056":"CAM_SIOC"},"GPIO28":{"0":"None"},"GPIO29":{"0":"None"},"GPIO30":{"0":"None"},"GPIO31":{"0":"None"},"GPIO32":{"4928":"CAM_PWDN"},"GPIO33":{"0":"None"},"GPIO34":{"5094":"CAM_DATA7"},"GPIO35":{"5095":"CAM_DATA8"},"GPIO36":{"5092":"CAM_DATA5"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"5093":"CAM_DATA6"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
20:35:53.118 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_F063A0","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
20:35:53.121 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32-webcam.bin","RestartReason":"Software reset CPU","Uptime":"0T01:27:56","StartupUTC":"2021-06-15T18:07:57","Sleep":50,"CfgHolder":4617,"BootCount":13,"BCResetTime":"2021-06-07T17:54:22","SaveCount":30}}
20:35:53.124 RSL: STATUS2 = {"StatusFWR":{"Version":"9.4.0(webcam)","BuildDateTime":"2021-04-23T10:10:09","Core":"1_0_6","SDK":"v3.3.5-1-g85c43024c","CpuFrequency":240,"Hardware":"ESP32-D0WDQ6","CR":"366/699"}}
20:35:53.126 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Penguins",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A0A000000000000","00000080","00006000","00000000"]}}
20:35:53.132 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":1350,"Free":1856,"Heap":125,"PsrMax":4095,"PsrFree":3345,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC78F","00140001","000000CF","010013C0","40000981","80004000","00200000","00000024"],"Drivers":"1,2,3,4,5,7,8,9,10,12,20,21,24,26,27,29,50,81","Sensors":"1,2,3,5,6,87"}}
20:35:53.135 RSL: STATUS5 = {"StatusNET":{"Hostname":"tasmota_F063A0-0928","IPAddress":"192.168.0.151","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.7","Mac":"24:0A:C4:F0:63:A0","Webserver":2,"WifiConfig":0,"WifiPower":17.0}}
20:35:53.138 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F063A0","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
20:35:53.141 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-06-15T19:35:53","Local":"2021-06-15T20:35:53","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"04:46","Sunset":"20:55"}}
20:35:53.146 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-06-15T20:35:53","ESP32":{"Temperature":73.3},"TempUnit":"C"}}
20:35:53.150 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-06-15T20:35:53","Uptime":"0T01:27:56","UptimeSec":5276,"Heap":127,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"Wifi":{"AP":1,"SSId":"Penguins","BSSId":"C0:C9:E3:53:82:F6","Channel":8,"RSSI":100,"Signal":-46,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
n/a

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Flash an ESP32 cam with tasmota-webcam. Attempt to process resultant mjpeg stream with py-mjpeg client code. (Using this library is just an easy example to reproduce, I've tried others that exhibit the same problem with the stream)
Using library https://pypi.org/project/py-mjpeg/

```
from mjpeg.client import MJPEGClient

url='http://david:81/cam.mjpeg'

# Create a new client thread
client = MJPEGClient(url)

# Allocate memory buffers for frames
bufs = client.request_buffers(65536, 50)
for b in bufs:
    client.enqueue_buffer(b)
    
# Start the client in a background thread
client.start()
# grab 4 frames from stream
i = 4
while i > 0:
    buf = client.dequeue_buffer()
    data = memoryview(buf.data)[:buf.used]
    f = open('rat.jpg', 'wb')
    f.write(data)
    f.close()
    client.enqueue_buffer(buf)
    i = i - 4
client.print_stats()
```

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
stream is processed without error.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
```
python3 
Traceback (most recent call last):
  File "/Users/martin/Library/Python/3.7/lib/python/site-packages/mjpeg/client.py", line 151, in run
    self.process_stream(s)
  File "/Users/martin/Library/Python/3.7/lib/python/site-packages/mjpeg/client.py", line 120, in process_stream
    timestamp, clen = read_mjpeg_frame(stream, boundary, mem, length)
  File "/Users/martin/Library/Python/3.7/lib/python/site-packages/mjpeg/__init__.py", line 152, in read_mjpeg_frame
    hdr = read_headers(stream, boundary)
  File "/Users/martin/Library/Python/3.7/lib/python/site-packages/mjpeg/__init__.py", line 38, in read_headers
    raise ProtoError('Boundary string expected, but not found')
mjpeg.ProtoError: Boundary string expected, but not found
```

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Moving this issue to Ideas. Thanks.
